version: '3.3'
services:
  database:
    image: mysql:5.7
    container_name: spring_app_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo-app
    volumes:
      - /home/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306

  spring-boot:
    image: adnenettayeb/demoapp:latest
    container_name: spring_app
    ports:
      - 8089:8089
    depends_on:
      - database
    restart: on-failure
